[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/"]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"
build_info = true
extra_output = ["metadata", "storageLayout"]

[fuzz]
runs = 256
